/**
 * "Your First Patient" Walkthrough
 * Complete workflow from finding a patient to closing an encounter
 */

import { Walkthrough } from '../types';

export const firstPatientWalkthrough: Walkthrough = {
  id: 'first-patient',
  title: 'Your First Patient',
  description: 'Learn how to search for a patient, open their chart, start an encounter, document findings, and sign the note. This is the core workflow you\'ll use every day.',
  estimatedMinutes: 8,
  difficulty: 'beginner',
  category: 'clinical',
  icon: '👨‍⚕️',
  steps: [
    {
      id: 'intro',
      title: 'Welcome to Your First Patient',
      description: 'Let\'s walk through the complete patient encounter workflow. We\'ll search for a patient, review their chart, document an encounter, and close the visit.',
      targetSelector: 'body',
      position: 'center',
      canSkip: false,
    },
    {
      id: 'click-patients',
      title: 'Navigate to Patients',
      description: 'Click on the "Patients" tab in the navigation bar to view your patient list.',
      targetSelector: '.nav span:nth-child(6)',
      position: 'bottom',
      action: 'click',
      canSkip: false,
    },
    {
      id: 'search-patient',
      title: 'Search for a Patient',
      description: 'Use the search bar at the top to find a patient. Try searching for a patient by last name or first name.',
      targetSelector: 'select',
      position: 'bottom',
      action: 'click',
      actionValue: 'Smith',
    },
    {
      id: 'open-patient-chart',
      title: 'Open Patient Chart',
      description: 'Click on a patient name to open their complete medical chart. This shows their demographics, history, medications, and more.',
      targetSelector: '.list-row:first-child',
      position: 'right',
      action: 'click',
    },
    {
      id: 'review-patient-info',
      title: 'Review Patient Information',
      description: 'Take a moment to review the patient\'s basic information, including contact details, date of birth, and medical history. This is displayed at the top of the chart.',
      targetSelector: '.panel:first-child',
      position: 'bottom',
      action: 'wait',
    },
    {
      id: 'start-encounter',
      title: 'Start an Encounter',
      description: 'Click the "+ Encounter" button to begin documenting today\'s visit. An encounter represents a single patient visit.',
      targetSelector: 'details:has(summary:contains("Encounter"))',
      position: 'bottom',
      action: 'click',
    },
    {
      id: 'add-chief-complaint',
      title: 'Enter Chief Complaint',
      description: 'Enter the patient\'s chief complaint - the main reason for today\'s visit. For example: "Rash on arms" or "Acne follow-up".',
      targetSelector: 'input[placeholder*="Chief"]',
      position: 'right',
      action: 'type',
      actionValue: 'Rash on both arms x 2 weeks',
    },
    {
      id: 'document-hpi',
      title: 'Document History of Present Illness',
      description: 'In the HPI section, document when the problem started, what makes it better or worse, and any associated symptoms. Be thorough but concise.',
      targetSelector: 'textarea',
      position: 'right',
      action: 'type',
      actionValue: 'Patient reports pruritic rash started 2 weeks ago...',
    },
    {
      id: 'add-exam-findings',
      title: 'Document Exam Findings',
      description: 'Record your physical examination findings in the Exam section. Describe what you see, where it\'s located, and any notable characteristics.',
      targetSelector: 'label:has-text("Exam") textarea',
      position: 'right',
      action: 'type',
      actionValue: 'Bilateral forearms with erythematous papular rash...',
    },
    {
      id: 'add-assessment',
      title: 'Add Assessment & Plan',
      description: 'Enter your diagnosis and treatment plan. Include the diagnosis, any prescriptions, and follow-up instructions.',
      targetSelector: 'label:has-text("Assessment") textarea',
      position: 'right',
      action: 'type',
      actionValue: 'Assessment: Contact dermatitis. Plan: Triamcinolone cream 0.1% BID...',
    },
    {
      id: 'save-encounter',
      title: 'Save the Encounter',
      description: 'Click "Save encounter" to save your documentation. This creates a draft note that you can continue editing.',
      targetSelector: 'button:has-text("Save encounter")',
      position: 'top',
      action: 'click',
    },
    {
      id: 'sign-note',
      title: 'Sign and Close the Encounter',
      description: 'Once you\'ve reviewed your documentation, change the encounter status to "Signed" to finalize the note. This locks the encounter and makes it official.',
      targetSelector: 'select:has(option:contains("Signed"))',
      position: 'left',
      action: 'click',
    },
    {
      id: 'completion',
      title: 'Congratulations!',
      description: 'You\'ve successfully completed your first patient encounter! You now know how to search for patients, document visits, and sign notes. This workflow is the foundation of using the system.',
      targetSelector: 'body',
      position: 'center',
      canSkip: false,
    },
  ],
};
