/**
 * "Full Skin Exam" Walkthrough
 * Complete body skin cancer screening documentation
 */

import { Walkthrough } from '../types';

export const skinCheckWalkthrough: Walkthrough = {
  id: 'skin-check',
  title: 'Full Body Skin Exam',
  description: 'Master the complete skin cancer screening workflow: systematic examination, lesion documentation, body diagram mapping, and patient education.',
  estimatedMinutes: 10,
  difficulty: 'intermediate',
  category: 'clinical',
  icon: '🔍',
  steps: [
    {
      id: 'intro',
      title: 'Skin Cancer Screening',
      description: 'A full body skin exam is a systematic head-to-toe examination to detect skin cancers. Proper documentation is critical for tracking lesions over time and billing.',
      targetSelector: 'body',
      position: 'center',
    },
    {
      id: 'open-patient',
      title: 'Open Patient Chart',
      description: 'Select the patient scheduled for skin cancer screening. Review their history of skin cancers, family history, and previous biopsy results.',
      targetSelector: '.list-row:first-child',
      position: 'right',
      action: 'click',
    },
    {
      id: 'create-encounter',
      title: 'Start Skin Check Encounter',
      description: 'Create a new encounter for the skin check. The chief complaint should be "Full body skin exam" or "Skin cancer screening".',
      targetSelector: 'details:has(summary:contains("Encounter"))',
      position: 'bottom',
      action: 'click',
    },
    {
      id: 'chief-complaint',
      title: 'Document Chief Complaint',
      description: 'Enter the chief complaint and relevant history: any new or changing lesions, personal history of skin cancer, family history, sun exposure, and tanning bed use.',
      targetSelector: 'input[placeholder*="Chief"]',
      position: 'right',
      action: 'type',
      actionValue: 'Annual full body skin exam. Hx of 2 BCCs excised. No new concerning lesions noted by patient.',
    },
    {
      id: 'systematic-exam',
      title: 'Systematic Examination',
      description: 'Document a complete head-to-toe examination. Use a template or systematic approach: scalp, face, neck, chest, back, arms, hands, legs, feet, and intertriginous areas.',
      targetSelector: 'label:has-text("Exam") textarea',
      position: 'right',
      action: 'type',
      actionValue: 'Full body skin exam: Scalp: No concerning lesions. Face/ears: Multiple actinic keratoses on forehead and temples. Chest/back: Numerous benign-appearing nevi...',
    },
    {
      id: 'document-lesions',
      title: 'Document Specific Lesions',
      description: 'For any concerning lesions, document: location, size, color, borders, evolution. Use the ABCDE criteria for melanoma screening (Asymmetry, Border, Color, Diameter, Evolution).',
      targetSelector: 'textarea',
      position: 'right',
      action: 'type',
      actionValue: 'Notable lesions: 1) L shoulder: 6mm brown papule, symmetric, regular borders, homogeneous color - benign nevus. 2) R upper back: 8mm pink scaly plaque - suggestive BCC.',
    },
    {
      id: 'body-diagram',
      title: 'Mark on Body Diagram',
      description: 'Navigate to the body diagram tool and mark the location of all concerning lesions. This creates a visual map for tracking lesions over time.',
      targetSelector: '.nav span:has-text("Document")',
      position: 'bottom',
      action: 'click',
    },
    {
      id: 'photography',
      title: 'Photograph Concerning Lesions',
      description: 'Take dermoscopic or clinical photos of any lesions you\'re monitoring or biopsying. Include a ruler for scale. Tag each photo with the specific body location.',
      targetSelector: 'details:has(summary:contains("Photo"))',
      position: 'bottom',
      action: 'click',
    },
    {
      id: 'plan-biopsies',
      title: 'Plan Biopsies if Needed',
      description: 'For suspicious lesions, order biopsies now. Document which lesions you\'re biopsying and why. Create orders for each biopsy with clinical description.',
      targetSelector: 'details:has(summary:contains("Order"))',
      position: 'bottom',
      action: 'wait',
    },
    {
      id: 'assessment-plan',
      title: 'Assessment and Plan',
      description: 'Document your assessment: number of lesions examined, any concerning findings, biopsies performed, and follow-up plan. Include patient education about sun protection.',
      targetSelector: 'label:has-text("Assessment") textarea',
      position: 'right',
      action: 'type',
      actionValue: 'Assessment: Annual skin cancer screening. 2 actinic keratoses treated with LN2. 1 BCC suspected on R upper back - biopsy performed today. Plan: Results in 1 week, annual f/u.',
    },
    {
      id: 'patient-education',
      title: 'Patient Education',
      description: 'Educate patient on: self-skin exams, ABCDE criteria, sun protection (sunscreen SPF 30+, protective clothing, avoiding peak sun), and when to call with concerns.',
      targetSelector: 'body',
      position: 'center',
      action: 'wait',
    },
    {
      id: 'billing',
      title: 'Proper Billing',
      description: 'Full body skin exams bill with appropriate E&M code plus any procedures (biopsies, cryotherapy). If high-risk patient, may qualify for specific screening codes.',
      targetSelector: 'details:has(summary:contains("Charge"))',
      position: 'bottom',
      action: 'wait',
    },
    {
      id: 'completion',
      title: 'Skin Check Complete!',
      description: 'Great job! You\'ve completed a thorough skin cancer screening. Remember: systematic examination, detailed documentation, body mapping, photography, and patient education are key to quality care.',
      targetSelector: 'body',
      position: 'center',
    },
  ],
};
