import type { Express } from "express";
import { apiLimiter, portalLimiter, uploadLimiter } from "../middleware/rateLimiter";
import { healthRouter } from "./health";
import { authRouter } from "./auth";
import { patientsRouter } from "./patients";
import { appointmentsRouter } from "./appointments";
import { providersRouter } from "./providers";
import { locationsRouter } from "./locations";
import { appointmentTypesRouter } from "./appointmentTypes";
import { availabilityRouter } from "./availability";
import { auditRouter } from "./audit";
import { auditReportsRouter } from "./auditReports";
import { encountersRouter } from "./encounters";
import { documentsRouter } from "./documents";
import { photosRouter } from "./photos";
import { chargesRouter } from "./charges";
import { diagnosesRouter } from "./diagnoses";
import { tasksRouter } from "./tasks";
import { taskTemplatesRouter } from "./taskTemplates";
import { messagesRouter } from "./messages";
import { fhirRouter } from "./fhir";
import { analyticsRouter } from "./analytics";
import { hl7Router } from "./hl7";
import { vitalsRouter } from "./vitals";
import { uploadRouter } from "./upload";
import { vitalsWriteRouter } from "./vitalsWrite";
import { chronicConditionsRouter } from "./chronicConditions";
import { templatesRouter } from "./templates";
import { ordersRouter } from "./orders";
import { interopRouter } from "./interop";
import { reportsRouter } from "./reports";
import { fhirPayloadRouter } from "./fhirPayload";
import { presignRouter } from "./presign";
import { serveUploadsRouter } from "./serveUploads";
import feeSchedulesRouter from "./feeSchedules";
import { cptCodesRouter } from "./cptCodes";
import { icd10CodesRouter } from "./icd10Codes";
import { claimsRouter } from "./claims";
import { adaptiveLearningRouter } from "./adaptiveLearning";
import { noteTemplatesRouter } from "./noteTemplates";
import { messagingRouter } from "./messaging";
import { recallsRouter } from "./recalls";
import { prescriptionsRouter } from "./prescriptions";
import { drugInteractionsRouter } from "./drugInteractions";
import { refillRequestsRouter } from "./refillRequests";
import { rxChangeRequestsRouter } from "./rxChangeRequests";
import { medicationsRouter } from "./medications";
import { pharmaciesRouter } from "./pharmacies";
import { rxHistoryRouter } from "./rxHistory";
import { kioskRouter } from "./kiosk";
import { consentFormsRouter } from "./consentForms";
import { patientPortalRouter } from "./patientPortal";
import { patientPortalDataRouter } from "./patientPortalData";
import { visitSummariesRouter } from "./visitSummaries";
import { patientMessagesRouter } from "./patientMessages";
import { patientPortalMessagesRouter } from "./patientPortalMessages";
import { cannedResponsesRouter } from "./cannedResponses";
import { patientSchedulingRouter, providerSchedulingRouter } from "./patientScheduling";
import { bodyDiagramRouter } from "./bodyDiagram";
import { bodyMapRouter } from "./bodyMap";
import { bodyMapMarkersRouter } from "./bodyMapMarkers";
import { smsRouter } from "./sms";
import { smsConsentRouter } from "./smsConsent";
import { smsAuditRouter } from "./smsAudit";
import { priorAuthRouter } from "./priorAuth";
import timeBlocksRouter from "./timeBlocks";
import waitlistRouter from "./waitlist";
import handoutsRouter from "./handouts";
import aiAnalysisRouter from "./aiAnalysis";
import aiLesionAnalysisRouter from "./aiLesionAnalysis";
import lesionsRouter from "./lesions";
import lesionTrackingRouter from "./lesionTracking";
import woundsRouter from "./wounds";
import aiNoteDraftingRouter from "./aiNoteDrafting";
import voiceTranscriptionRouter from "./voiceTranscription";
import cdsRouter from "./cds";
import { faxRouter } from "./fax";
import { notesRouter } from "./notes";
import { directMessagingRouter } from "./directMessaging";
import { clearinghouseRouter } from "./clearinghouse";
import { qualityMeasuresRouter } from "./qualityMeasures";
import { referralsRouter } from "./referrals";
import { registryRouter } from "./registry";
import { diseaseRegistryRouter } from "./diseaseRegistry";
import telehealthRouter from "./telehealth";
import { portalBillingRouter } from "./portalBilling";
import { portalIntakeRouter } from "./portalIntake";
import { labOrdersRouter } from "./labOrders";
import { labResultsRouter } from "./labResults";
import { labVendorsRouter } from "./labVendors";
import { dermPathRouter } from "./dermPath";
import { resultFlagsRouter } from "./resultFlags";
import ambientScribeRouter from "./ambientScribe";
import priorAuthRequestsRouter from "./priorAuthRequests";
import { erxRouter } from "./erx";
import { pdmpRouter } from "./pdmp";
import adminRouter from "./admin";
import { aiAgentConfigsRouter } from "./aiAgentConfigs";
import { inventoryRouter } from "./inventory";
import { inventoryUsageRouter } from "./inventoryUsage";
import { payerPaymentsRouter } from "./payerPayments";
import { patientPaymentsRouter } from "./patientPayments";
import { statementsRouter } from "./statements";
import { batchesRouter } from "./batches";
import { billsRouter } from "./bills";
import { financialMetricsRouter } from "./financialMetrics";
import { integrationsRouter } from "./integrations";
import { frontDeskRouter } from "./frontDesk";
import { eligibilityRouter } from "./eligibility";
import { checkInRouter } from "./checkIn";
import { billingRouter } from "./billing";
import { cosmeticTreatmentsRouter } from "./cosmeticTreatments";
import { cosmeticRouter } from "./cosmetic";
import { protocolsRouter } from "./protocols";
import { intakeRouter } from "./intake";
import { intakeFormsRouter } from "./intakeForms";
import { staffSchedulingRouter } from "./staffScheduling";
import { revenueCycleRouter } from "./revenueCycle";
import { patientEngagementRouter } from "./patientEngagement";
import { externalIntegrationsRouter } from "./externalIntegrations";
import { communicationsRouter } from "./communications";
import { notificationsRouter } from "./notifications";
import { jobsRouter } from "./jobs";
import { eventsRouter } from "./events";
import { waitlistRecallRouter } from "./waitlistRecall";
import { severityScoresRouter } from "./severityScores";
import { patientFlowRouter, roomsRouter } from "./patientFlow";
import { superbillsRouter } from "./superbills";
import { quickpicksRouter } from "./quickpicks";
import { claimsSubmissionRouter } from "./claimsSubmission";
import { procedureTemplatesRouter } from "./procedureTemplates";
import { consentsRouter } from "./consents";
import { mipsRouter } from "./mips";
import { allergiesRouter } from "./allergies";
import { mohsRouter } from "./mohs";
import biopsyRouter from "./biopsy";
import patchTestRouter from "./patchTest";
import { phototherapyRouter } from "./phototherapy";
import telemedicineRouter from "./telemedicine";
import { surveysRouter } from "./surveys";
import { productsRouter } from "./products";
import { referralTrackingRouter } from "./referralTracking";
import waitTimeRouter from "./waitTime";
import { remindersRouter } from "./reminders";

export function registerRoutes(app: Express) {
  app.use("/health", healthRouter);
  app.use("/api/auth", authRouter);
  app.use("/api/patients", patientsRouter);
  app.use("/api/appointments", appointmentsRouter);
  app.use("/api/providers", providersRouter);
  app.use("/api/locations", locationsRouter);
  app.use("/api/appointment-types", appointmentTypesRouter);
  app.use("/api/availability", availabilityRouter);
  app.use("/api/audit", auditRouter);
  app.use("/api/audit-reports", auditReportsRouter);
  app.use("/api/encounters", encountersRouter);
  app.use("/api/documents", documentsRouter);
  app.use("/api/photos", photosRouter);
  app.use("/api/charges", chargesRouter);
  app.use("/api/diagnoses", diagnosesRouter);
  app.use("/api/tasks", tasksRouter);
  app.use("/api/task-templates", taskTemplatesRouter);
  app.use("/api/messages", messagesRouter);
  app.use("/api/fhir", fhirRouter);
  app.use("/api/analytics", analyticsRouter);
  app.use("/api/hl7", hl7Router);
  app.use("/api/vitals", vitalsRouter);
  app.use("/api/vitals/write", vitalsWriteRouter);
  app.use("/api/chronic-conditions", chronicConditionsRouter);
  app.use("/api/upload", uploadLimiter, uploadRouter);
  app.use("/api/templates", templatesRouter);
  app.use("/api/orders", ordersRouter);
  app.use("/api/interop", interopRouter);
  app.use("/api/reports", reportsRouter);
  app.use("/api/interop/fhir-payloads", fhirPayloadRouter);
  app.use("/api/presign", presignRouter);
  app.use("/api/uploads", serveUploadsRouter);
  app.use("/api/fee-schedules", feeSchedulesRouter);
  app.use("/api/cpt-codes", cptCodesRouter);
  app.use("/api/icd10-codes", icd10CodesRouter);
  app.use("/api/claims", claimsRouter);
  app.use("/api/adaptive", adaptiveLearningRouter);
  app.use("/api/note-templates", noteTemplatesRouter);
  app.use("/api/messaging", messagingRouter);
  app.use("/api/recalls", recallsRouter);
  app.use("/api/prescriptions", prescriptionsRouter);
  app.use("/api/drugs", drugInteractionsRouter);
  app.use("/api/refill-requests", refillRequestsRouter);
  app.use("/api/rx-change-requests", rxChangeRequestsRouter);
  app.use("/api/medications", medicationsRouter);
  app.use("/api/pharmacies", pharmaciesRouter);
  app.use("/api/rx-history", rxHistoryRouter);
  app.use("/api/erx", erxRouter);
  app.use("/api/pdmp", pdmpRouter);
  app.use("/api/admin", adminRouter);
  app.use("/api/prior-auth", priorAuthRouter);
  app.use("/api/time-blocks", timeBlocksRouter);
  app.use("/api/waitlist", waitlistRouter);
  app.use("/api/handouts", handoutsRouter);
  app.use("/api/kiosk", kioskRouter);
  app.use("/api/consent-forms", consentFormsRouter);
  app.use("/api/patient-portal", portalLimiter, patientPortalRouter);
  app.use("/api/patient-portal-data", portalLimiter, patientPortalDataRouter);
  app.use("/api/visit-summaries", visitSummariesRouter);
  app.use("/api/patient-messages", patientMessagesRouter);
  app.use("/api/patient-portal/messages", patientPortalMessagesRouter);
  app.use("/api/canned-responses", cannedResponsesRouter);
  app.use("/api/patient-portal/scheduling", portalLimiter, patientSchedulingRouter);
  app.use("/api/patient-portal/billing", portalLimiter, portalBillingRouter);
  app.use("/api/patient-portal/intake", portalLimiter, portalIntakeRouter);
  app.use("/api/scheduling", apiLimiter, providerSchedulingRouter);
  app.use("/api/body-diagram", bodyDiagramRouter);
  app.use("/api", bodyMapRouter);
  app.use("/api/body-map-markers", apiLimiter, bodyMapMarkersRouter);
  // Note: procedure-sites routes are prefixed /procedure-sites in bodyMapMarkersRouter, so mount at /api
  // But we need to make it more specific to avoid catching other routes
  // Moving all /api/procedure-sites/* routes to their own mount point would require refactoring
  // For now, the routes are available at /api/body-map-markers/procedure-sites
  app.use("/api/front-desk", frontDeskRouter);
  app.use("/api/sms", smsRouter);
  app.use("/api/sms-consent", smsConsentRouter);
  app.use("/api/sms-audit", smsAuditRouter);
  app.use("/api/ai-analysis", aiAnalysisRouter);
  app.use("/api/ai-lesion-analysis", aiLesionAnalysisRouter);
  app.use("/api/lesions", lesionsRouter);
  app.use("/api/lesion-tracking", lesionTrackingRouter);
  app.use("/api/wounds", woundsRouter);
  app.use("/api/protocols", protocolsRouter);
  app.use("/api/ai-notes", aiNoteDraftingRouter);
  app.use("/api/voice", voiceTranscriptionRouter);
  app.use("/api/cds", cdsRouter);
  app.use("/api/fax", faxRouter);
  app.use("/api/notes", notesRouter);
  app.use("/api/direct", directMessagingRouter);
  app.use("/api/clearinghouse", clearinghouseRouter);
  app.use("/api/quality", qualityMeasuresRouter);
  app.use("/api/mips", mipsRouter);
  app.use("/api/referrals", referralsRouter);
  app.use("/api/registry", registryRouter);
  app.use("/api/disease-registry", diseaseRegistryRouter);
  app.use("/api/telehealth", telehealthRouter);
  app.use("/api/lab-orders", labOrdersRouter);
  app.use("/api/lab-results", labResultsRouter);
  app.use("/api/lab-vendors", labVendorsRouter);
  app.use("/api/dermpath", dermPathRouter);
  app.use("/api/result-flags", resultFlagsRouter);
  app.use("/api/ambient", ambientScribeRouter);
  app.use("/api/prior-auth-requests", priorAuthRequestsRouter);
  app.use("/api/ai-agent-configs", aiAgentConfigsRouter);
  app.use("/api/inventory", inventoryRouter);
  app.use("/api/inventory-usage", inventoryUsageRouter);
  app.use("/api/payer-payments", payerPaymentsRouter);
  app.use("/api/patient-payments", patientPaymentsRouter);
  app.use("/api/integrations", integrationsRouter);
  app.use("/api/statements", statementsRouter);
  app.use("/api/batches", batchesRouter);
  app.use("/api/bills", billsRouter);
  app.use("/api/financial-metrics", financialMetricsRouter);
  app.use("/api/eligibility", eligibilityRouter);
  app.use("/api/check-in", checkInRouter);
  app.use("/api/billing", billingRouter);
  app.use("/api/cosmetic-treatments", cosmeticTreatmentsRouter);
  app.use("/api/cosmetic", cosmeticRouter);
  app.use("/api/intake", intakeRouter);
  app.use("/api/intake-forms", intakeFormsRouter);
  app.use("/api/staff-scheduling", apiLimiter, staffSchedulingRouter);
  app.use("/api/rcm", revenueCycleRouter);
  app.use("/api/engagement", patientEngagementRouter);
  app.use("/api/communications", communicationsRouter);
  app.use("/api/notifications", notificationsRouter);
  app.use("/api/jobs", jobsRouter);
  app.use("/api/events", eventsRouter);
  app.use("/api/waitlist-recall", waitlistRecallRouter);
  app.use("/api/external-integrations", externalIntegrationsRouter);
  app.use("/api/severity-scores", severityScoresRouter);
  app.use("/api/patient-flow", patientFlowRouter);
  app.use("/api/rooms", roomsRouter);
  app.use("/api/superbills", superbillsRouter);
  app.use("/api/quickpicks", quickpicksRouter);
  app.use("/api/claims-submission", claimsSubmissionRouter);
  app.use("/api/procedure-templates", procedureTemplatesRouter);
  app.use("/api/procedures", procedureTemplatesRouter);
  app.use("/api/consents", consentsRouter);
  app.use("/api/allergies", allergiesRouter);
  app.use("/api/mohs", mohsRouter);
  app.use("/api/biopsies", biopsyRouter);
  app.use("/api/patch-test", patchTestRouter);
  app.use("/api/phototherapy", phototherapyRouter);
  app.use("/api/telemedicine", telemedicineRouter);
  app.use("/api/surveys", surveysRouter);
  app.use("/api/products", productsRouter);
  app.use("/api/referral-sources", referralTrackingRouter);
  app.use("/api/wait-time", waitTimeRouter);
}
